# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Silvio Schwarz
email: admin@silvioschwarz.com
description: >- # this means to ignore newlines until "baseurl:"
    Geophysics <br> Machine Learning <br> Psychoanalysis <br> Nature
baseurl: / # the subpath of your site, e.g. /blog
url: http://www.silvioschwarz.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: slvschwrz
github_username:  silvioschwarz



author:
  name:           'Silvio Schwarz'
  url:             www.silvioschwarz.com

paginate:         5

# Custom vars

github:		
  repo:         https://github.com/silvioschwarz/

instagram_url:	https://instagram.com/slv.schwrz/
twitter_url:	https://twitter.com/slvschwrz/
linkedin_url:	https://www.linkedin.com/in/silvioschwarz/

art:		http://instagram.com/amethodtothismadness/
music:		http://instagram.com/neros.torch/
cv:		https://silvioschwarz.github.io/CV/
paypal:		https://www.paypal.com/paypalme/silvioschwarz8/9
nature:		http://www.silvioschwarz.com/selvaggio/
psychoBlog:	http://www.silvioschwarz.com/psychoanalythis/
nerostorch:	http://www.silvioschwarz.com/nerostorch/
amethodtomadness:	 http://www.silvioschwarz.com/amethodtomadness/
meaningfromexperience:	 http://www.silvioschwarz.com/meaningfromexperience/

sourcetosite:	http://www.silvioschwarz.com/seismology/eqs2s/
terremotopi:	https://silvioschwarz.github.io/TerremotoPi/
liveseismo:	https://www.silvioschwarz.com/seismology/terremotopi/
seismology:	https://www.silvioschwarz.com/seismology/




# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Silvio Schwarz"
  -
    scope:
      path: "amethodtomadness"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      category: amethodtomadness
  -
    scope:
      path: "nerostorch"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      category: nerostorch
  -
    scope:
      path: "meaningfromexperience"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      category: meaningfromexperience
  -
    scope:
      path: "psychoanalythis"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      category: psychoanalythis
  -
    scope:
      path: "selvaggio"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      category: selvaggio




highlighter:      pygments

# Permalinks
permalink:        pretty

